#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Spaces fork of calamares-nixos-extensions/modules/nixos/main.py.
#
# Differences vs upstream:
#   - emits `/mnt/etc/nixos/flake.nix` + `flake.lock` referencing the
#     spaces flake. flake.nix points `inputs.spaces.url` at upstream
#     `github:generational-infrastructure/spaces-os`; flake.lock is
#     generated at install time via `nix flake lock --override-input
#     spaces path:<staged> --override-input spaces/<name> path:<staged>
#     ...` so every input resolves against the live ISO's nix store.
#     We drive `nix build` directly + `nixos-install --system <toplevel>`
#     because `nixos-install --flake` would rewrite flake.lock and trip
#     the lock-rewrite cycle in nix#9339.
#   - drops desktop-environment branching (`packagechooser_*` reads,
#     cfggnome/plasma6/...) — spaces module owns the desktop;
#   - drops upstream-opinion blocks (cfgfirefox, cfgmisc, cfgpkgs,
#     cfgtail, cfgunfree, cfglatestkernel) so the spaces module is the
#     single source of truth for system-wide defaults;
#   - generated `configuration.nix` is a thin host-overlay module:
#     hostname, user, locale, keyboard, bootloader, fs come from
#     Calamares; everything else from `spaces.nixosModules.spaces`;
#   - autologin is wired through `services.greetd` (what spaces uses)
#     rather than `services.displayManager.autoLogin`.
#
# Boot/LUKS/btrfs-subvol logic preserved verbatim from upstream — those
# are correctness-critical and not spaces-specific.

import configparser
import gettext
import json
import os
import re
import subprocess

import libcalamares

_ = gettext.translation(
    "calamares-python",
    localedir=libcalamares.utils.gettext_path(),
    languages=libcalamares.utils.gettext_languages(),
    fallback=True,
).gettext


# ---------------------------------------------------------------------------
# configuration.nix template fragments
# ---------------------------------------------------------------------------
#
# The generated configuration.nix is a thin host-overlay module. It does
# NOT carry an `imports = [ ./hardware-configuration.nix ];` line: both
# `./configuration.nix` and `./hardware-configuration.nix` are listed as
# modules in the generated flake.nix, alongside `spaces.nixosModules.spaces`.

cfghead = """# Host-specific overlay generated by the Spaces OS graphical installer.
# Spaces defaults come from `spaces.nixosModules.spaces` (wired in via
# flake.nix); this file only carries per-install choices.
{ ... }:

{
"""

cfgbootefi = """  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

"""

cfgbootbios = """  # Bootloader.
  boot.loader.grub.enable = true;
  boot.loader.grub.device = "@@bootdev@@";
  boot.loader.grub.useOSProber = true;

"""

cfgbootbiosbtrfs = """  # Bootloader.
  boot.loader.grub.enable = true;
  boot.loader.grub.device = "@@bootdev@@";
  boot.loader.grub.useOSProber = true;
  # Use provided UUIDs instead of blkid probing (required for btrfs subvolumes)
  boot.loader.grub.fsIdentifier = "provided";

"""

cfgbootnone = """  # Disable bootloader.
  boot.loader.grub.enable = false;

"""

cfgbootgrubcrypt = """  # Setup keyfile
  boot.initrd.secrets = {
    "/boot/crypto_keyfile.bin" = null;
  };

  boot.loader.grub.enableCryptodisk = true;

"""

cfgnetworkmanager = """  # Enable networking
  networking.networkmanager.enable = true;

"""

cfgtime = """  # Set your time zone.
  time.timeZone = "@@timezone@@";

"""

cfglocale = """  # Select internationalisation properties.
  i18n.defaultLocale = "@@LANG@@";

"""

cfglocaleextra = """  i18n.extraLocaleSettings = {
    LC_ADDRESS = "@@LC_ADDRESS@@";
    LC_IDENTIFICATION = "@@LC_IDENTIFICATION@@";
    LC_MEASUREMENT = "@@LC_MEASUREMENT@@";
    LC_MONETARY = "@@LC_MONETARY@@";
    LC_NAME = "@@LC_NAME@@";
    LC_NUMERIC = "@@LC_NUMERIC@@";
    LC_PAPER = "@@LC_PAPER@@";
    LC_TELEPHONE = "@@LC_TELEPHONE@@";
    LC_TIME = "@@LC_TIME@@";
  };

"""

cfgkeymap = """  # Configure keymap in X11
  services.xserver.xkb = {
    layout = "@@kblayout@@";
    variant = "@@kbvariant@@";
  };

"""

cfgconsole = """  # Configure console keymap
  console.keyMap = "@@vconsole@@";

"""

cfgusers = """  # Define a user account. Don't forget to set a password with 'passwd'.
  users.users.@@username@@ = {
    isNormalUser = true;
    description = "@@fullname@@";
    extraGroups = [ "networkmanager" "wheel" ];
  };

"""

# Spaces auto-logs into niri via greetd. Point greetd at the user
# Calamares created (overrides spaces's `lib.mkDefault "alice"`).
cfggreetd = """  # Auto-login the installer-created user into the niri session.
  services.greetd.settings.default_session.user = "@@username@@";

"""

cfgtail = """  # NixOS release this install was first set up against. Don't change
  # this value across upgrades unless you know what you're doing — see
  # `man configuration.nix` for the rationale.
  system.stateVersion = "@@nixosversion@@";
}
"""

# ---------------------------------------------------------------------------
# Wrapper flake template
# ---------------------------------------------------------------------------
#
# We emit a real wrapper flake at /mnt/etc/nixos pointing at the canonical
# upstream `github:generational-infrastructure/spaces-os`. The matching
# `flake.lock` is generated on the fly at install time:
#
#   nix flake lock <wrapper> --override-input spaces path:<SPACES_FLAKE>
#                            --override-input spaces/<NAME> path:<PATH> ...
#
# `<SPACES_FLAKE>` is the pre-staged spaces store path. The per-input
# overrides come from `INPUT_OVERRIDES` — a `{ name → store path }` map
# covering every direct input spaces declares — so the resulting lock
# pins spaces AND every transitive input declared by spaces to a `path:`
# reference into the live ISO's nix store. The install needs no network.
#
# After locking we drive `nix build` ourselves (with
# `--no-write-lock-file` so the freshly written lock isn't rewritten
# under us) and hand the toplevel to `nixos-install --system <path>`.
# `nixos-install --flake` would re-lock the wrapper at install time and
# trip the path-flake lock-rewrite cycle (nix#9339, unfixed 2026-04).
#
# Both values live in a JSON config file rather than being substituted
# into this script at package build time. Build-time substitution made
# the calamares-spaces-extensions derivation depend on the spaces flake
# source path, so any unrelated repo edit invalidated the package. The
# config file is generated at ISO build time (see
# modules/nixos/installer-iso.nix); tests point `CALAMARES_SPACES_CONFIG`
# at a fixture they control. `@@hostname@@`, `@@system@@`,
# `@@extra_modules@@` are filled at install time from globalstorage.

_SPACES_CONFIG_PATH = os.environ.get(
    "CALAMARES_SPACES_CONFIG", "/etc/calamares-spaces/install.json"
)
try:
    with open(_SPACES_CONFIG_PATH, "r") as _fh:
        _spaces_config = json.load(_fh)
    SPACES_FLAKE_PATH = _spaces_config["spacesFlake"]
    INPUT_OVERRIDES = _spaces_config.get("inputOverrides", {})
except FileNotFoundError:
    # No config staged — render functions still work for unit-test
    # introspection, but `run()` will fail when it tries to lock the
    # wrapper flake without a spaces path.
    SPACES_FLAKE_PATH = None
    INPUT_OVERRIDES = {}

flake_template = """{
  description = "Auto-generated by the Spaces OS graphical installer.";

  # Upstream source of truth. Run `nix flake update spaces` to refresh.
  inputs.spaces.url = "github:generational-infrastructure/spaces-os";

  outputs = inputs: {
    nixosConfigurations.@@hostname@@ = inputs.spaces.lib.mkSystem {
      system = "@@system@@";
      hostName = "@@hostname@@";
      modules = [
        ./configuration.nix
        ./hardware-configuration.nix
@@extra_modules@@      ];
    };
  };
}
"""


def env_is_set(name):
    envValue = os.environ.get(name)
    return not (envValue is None or envValue == "")


def generateProxyStrings():
    proxyEnv = []
    for var in ("http_proxy", "https_proxy", "HTTP_PROXY", "HTTPS_PROXY"):
        if env_is_set(var):
            proxyEnv.append("{}={}".format(var, os.environ.get(var)))
    if proxyEnv:
        proxyEnv.insert(0, "env")
    return proxyEnv


def pretty_name():
    return _("Installing Spaces OS.")


status = pretty_name()


def pretty_status_message():
    return status


def catenate(d, key, *values):
    """Set `d[key]` to the concatenation of `values`, unless any value is None."""
    if [v for v in values if v is None]:
        return
    d[key] = "".join(values)


def fix_btrfs_subvolumes(hardware_config, partitions):
    """Fix btrfs subvolume options in hardware-configuration.nix.

    `nixos-generate-config` writes `subvol=<mount-point>` instead of the
    actual subvolume names. Map mount points back to subvolume names
    (mirroring the layout `mount.conf` configures).
    """
    subvol_map = {
        "/home": "home",
        "/nix": "nix",
    }

    root_is_btrfs = any(
        p.get("mountPoint") == "/" and p.get("fs") == "btrfs" for p in partitions
    )
    if not root_is_btrfs:
        return hardware_config

    libcalamares.utils.debug("Fixing btrfs subvolume configuration")
    for mount_point, correct_subvol in subvol_map.items():
        pattern = r'(fileSystems\."{}"[^;]*"subvol=)[^"]*"'.format(
            re.escape(mount_point)
        )
        replacement = r'\g<1>{}"'.format(correct_subvol)
        hardware_config = re.sub(pattern, replacement, hardware_config, flags=re.DOTALL)
    return hardware_config


def render_configuration(gs, ngc_cfg):
    """Pure builder: assemble configuration.nix text from globalstorage.

    Returns the rendered configuration string. Side effects (LUKS
    keyfile creation, hardware-configuration.nix generation) live in
    `run`; keeping the builder pure makes it unit-testable against a
    stubbed `libcalamares` in `checks/installer-config-gen.nix`.
    """
    cfg = cfghead
    variables = {}

    fw_type = gs.value("firmwareType")
    bootdev = (
        "nodev"
        if gs.value("bootLoader") is None
        else gs.value("bootLoader")["installPath"]
    )
    partitions = gs.value("partitions") or []

    # Bootloader.
    root_is_btrfs = any(
        p.get("mountPoint") == "/" and p.get("fs") == "btrfs" for p in partitions
    )
    if fw_type == "efi":
        cfg += cfgbootefi
    elif bootdev != "nodev":
        cfg += cfgbootbiosbtrfs if root_is_btrfs else cfgbootbios
        catenate(variables, "bootdev", bootdev)
    else:
        cfg += cfgbootnone

    # Encrypted swap devices (nixos-generate-config doesn't notice them).
    for part in partitions:
        if (
            part.get("claimed") is True
            and part.get("fsName") in ("luks", "luks2")
            and part.get("device") is not None
            and part.get("fs") == "linuxswap"
        ):
            cfg += '  boot.initrd.luks.devices."{}".device = "/dev/disk/by-uuid/{}";\n'.format(
                part["luksMapperName"], part["uuid"]
            )

    cfg += cfgnetworkmanager

    if gs.value("locationRegion") is not None and gs.value("locationZone") is not None:
        cfg += cfgtime
        catenate(
            variables,
            "timezone",
            gs.value("locationRegion"),
            "/",
            gs.value("locationZone"),
        )

    if gs.value("localeConf") is not None:
        localeconf = dict(gs.value("localeConf"))
        locale = localeconf.pop("LANG").split("/")[0]
        cfg += cfglocale
        catenate(variables, "LANG", locale)
        if (
            len(set(localeconf.values())) != 1
            or list(set(localeconf.values()))[0] != locale
        ):
            cfg += cfglocaleextra
            for conf in localeconf:
                catenate(variables, conf, localeconf[conf].split("/")[0])

    if (
        gs.value("keyboardLayout") is not None
        and gs.value("keyboardVariant") is not None
    ):
        cfg += cfgkeymap
        catenate(variables, "kblayout", gs.value("keyboardLayout"))
        catenate(variables, "kbvariant", gs.value("keyboardVariant"))

        vconsole = _resolve_vconsole(gs)
        if vconsole:
            cfg += cfgconsole
            catenate(variables, "vconsole", vconsole)

    if gs.value("username") is not None:
        cfg += cfgusers
        catenate(variables, "username", gs.value("username"))
        catenate(variables, "fullname", gs.value("fullname") or "")
        cfg += cfggreetd

    cfg += cfgtail
    version = ".".join(subprocess.getoutput(["nixos-version"]).split(".")[:2])[:5]
    catenate(variables, "nixosversion", version)

    # Sanity: warn on unused variables / undefined patterns.
    for key in variables:
        pattern = "@@{}@@".format(key)
        if pattern not in cfg:
            libcalamares.utils.warning("Variable '{}' is not used.".format(key))
    for match in re.finditer(r"@@\w+@@", cfg):
        name = match.group(0)[2:-2]
        if name not in variables:
            libcalamares.utils.warning(
                "Variable '{}' is used but not defined.".format(name)
            )

    for key, value in variables.items():
        cfg = cfg.replace("@@{}@@".format(key), str(value))
    return cfg


def render_flake_nix(gs):
    """Render the wrapper `flake.nix` for the installed system."""
    expr = flake_template
    expr = expr.replace("@@hostname@@", gs.value("hostname") or "nixos")
    # Calamares ISOs are single-arch; mirror what the live ISO booted as.
    expr = expr.replace("@@system@@", os.uname().machine + "-linux")
    # If /etc/spaces-test-support exists, include the test-support module
    # in the installed system.  Used by the installer-gui VM test so the
    # post-install boot has serial console + niri software-rendering patch.
    # File-based (not env var) because GDM/GNOME sessions don't reliably
    # inherit environment.variables from /etc/set-environment.
    if os.path.exists("/etc/spaces-test-support"):
        extra = "        inputs.spaces.nixosModules.test-support\n"
    else:
        extra = ""
    expr = expr.replace("@@extra_modules@@", extra)
    return expr


def _resolve_vconsole(gs):
    """Return the console keymap name implied by the chosen X keyboard layout.

    Mirrors upstream's logic but extracted so `render_configuration` is
    side-effect-free for the unit test. `pkexec loadkeys` is invoked
    here because it actually applies the keymap to the live console;
    failure is non-fatal (we fall back to "no console keymap entry").
    """
    explicit = gs.value("keyboardVConsoleKeymap")
    if explicit is not None:
        explicit = explicit.strip()
        try:
            subprocess.check_output(
                ["pkexec", "loadkeys", explicit], stderr=subprocess.STDOUT
            )
            return explicit
        except subprocess.CalledProcessError as e:
            libcalamares.utils.error("loadkeys: {}".format(e.output))
            return None

    try:
        with open("/run/current-system/sw/share/systemd/kbd-model-map", "r") as f:
            rows = [line.split() for line in f if not line.startswith("#")]
    except OSError:
        return None

    layout = gs.value("keyboardLayout")
    variant = gs.value("keyboardVariant") or "-"
    matches = [r for r in rows if len(r) >= 4 and r[1] == layout]
    if not matches:
        return None
    vconsole = matches[0][0]
    for row in matches:
        if variant in row[3]:
            vconsole = row[0]
            break
    if vconsole in ("", "us", None):
        return None
    try:
        subprocess.check_output(
            ["pkexec", "loadkeys", vconsole], stderr=subprocess.STDOUT
        )
        return vconsole
    except subprocess.CalledProcessError as e:
        libcalamares.utils.error("loadkeys: {}".format(e.output))
        return None


def setup_luks_keyfile(gs, root_mount_point):
    """For BIOS+grub-cryptodisk setups, prime /boot/crypto_keyfile.bin.

    Mirrors upstream verbatim — correctness-critical, not spaces-specific.
    """
    cfg_extra = cfgbootgrubcrypt
    try:
        libcalamares.utils.host_env_process_output(
            ["mkdir", "-p", root_mount_point + "/boot"], None
        )
        libcalamares.utils.host_env_process_output(
            ["chmod", "0700", root_mount_point + "/boot"], None
        )
        libcalamares.utils.host_env_process_output(
            [
                "dd",
                "bs=512",
                "count=4",
                "if=/dev/random",
                "of=" + root_mount_point + "/boot/crypto_keyfile.bin",
                "iflag=fullblock",
            ],
            None,
        )
        libcalamares.utils.host_env_process_output(
            ["chmod", "600", root_mount_point + "/boot/crypto_keyfile.bin"], None
        )
    except subprocess.CalledProcessError:
        libcalamares.utils.error("Failed to create /boot/crypto_keyfile.bin")
        return None, (
            _("Failed to create /boot/crypto_keyfile.bin"),
            _("Check if you have enough free space on your partition."),
        )

    for part in gs.value("partitions"):
        if (
            part.get("claimed") is True
            and part.get("fsName") in ("luks", "luks2")
            and part.get("device") is not None
        ):
            cfg_extra += (
                '  boot.initrd.luks.devices."{}".keyFile = '
                '"/boot/crypto_keyfile.bin";\n'
            ).format(part["luksMapperName"])
            try:
                libcalamares.utils.host_env_process_output(
                    [
                        "cryptsetup",
                        "luksConvertKey",
                        "--hash",
                        "sha256",
                        "--pbkdf",
                        "pbkdf2",
                        part["device"],
                    ],
                    None,
                    part["luksPassphrase"],
                )
                libcalamares.utils.host_env_process_output(
                    [
                        "cryptsetup",
                        "luksAddKey",
                        "--hash",
                        "sha256",
                        "--pbkdf",
                        "pbkdf2",
                        part["device"],
                        root_mount_point + "/boot/crypto_keyfile.bin",
                    ],
                    None,
                    part["luksPassphrase"],
                )
            except subprocess.CalledProcessError:
                libcalamares.utils.error(
                    "Failed to add {} to /boot/crypto_keyfile.bin".format(
                        part["luksMapperName"]
                    )
                )
                return None, (
                    _("cryptsetup failed"),
                    _(
                        "Failed to add {} to /boot/crypto_keyfile.bin".format(
                            part["luksMapperName"]
                        )
                    ),
                )
    return cfg_extra, None


def run():
    """Generate the installed system's flake + configuration and run nixos-install."""
    global status
    status = _("Configuring Spaces OS")
    libcalamares.job.setprogress(0.1)

    ngc_cfg = configparser.ConfigParser()
    ngc_cfg["Defaults"] = {"Kernel": "lts"}
    ngc_cfg.read("/etc/nixos-generate-config.conf")

    gs = libcalamares.globalstorage
    root_mount_point = gs.value("rootMountPoint")

    # LUKS keyfile must be primed before configuration.nix is rendered
    # so we can append the boot.initrd.luks.devices.keyFile lines.
    fw_type = gs.value("firmwareType")
    boot_is_partition = False
    boot_is_encrypted = False
    root_is_encrypted = False
    for part in gs.value("partitions") or []:
        if part["mountPoint"] == "/":
            root_is_encrypted = part["fsName"] in ("luks", "luks2")
        elif part["mountPoint"] == "/boot":
            boot_is_partition = True
            boot_is_encrypted = part["fsName"] in ("luks", "luks2")

    luks_extra = ""
    if fw_type != "efi" and (
        (boot_is_partition and boot_is_encrypted)
        or (root_is_encrypted and not boot_is_partition)
    ):
        status = _("Setting up LUKS")
        libcalamares.job.setprogress(0.15)
        luks_extra, err = setup_luks_keyfile(gs, root_mount_point)
        if err is not None:
            return err

    cfg = render_configuration(gs, ngc_cfg)
    if luks_extra:
        # Inject LUKS-keyfile fragment right after cfgbootgrubcrypt's
        # natural slot — simplest is to prepend it inside the module
        # body (after the opening `{`). Configuration is order-insensitive.
        cfg = cfg.replace("{\n", "{\n" + luks_extra, 1)

    flake_nix = render_flake_nix(gs)

    status = _("Generating hardware configuration")
    libcalamares.job.setprogress(0.25)

    try:
        subprocess.check_output(
            ["pkexec", "nixos-generate-config", "--root", root_mount_point],
            stderr=subprocess.STDOUT,
        )
    except subprocess.CalledProcessError as e:
        if e.output is not None:
            libcalamares.utils.error(e.output.decode("utf8"))
        return (_("nixos-generate-config failed"), _(e.output.decode("utf8")))

    # Post-process hardware-configuration.nix (btrfs subvolumes only;
    # unfree-extraModulePackages stripping is dropped — spaces
    # `nixpkgs.config.allowUnfree = true` is already set).
    hwpath = root_mount_point + "/etc/nixos/hardware-configuration.nix"
    with open(hwpath, "r") as hf:
        htxt = hf.read()
    htxt_fixed = fix_btrfs_subvolumes(htxt, gs.value("partitions") or [])
    if htxt_fixed != htxt:
        libcalamares.utils.host_env_process_output(
            ["cp", "/dev/stdin", hwpath], None, htxt_fixed
        )

    # Lay down the generated host-overlay configuration.nix.
    config_path = os.path.join(root_mount_point, "etc/nixos/configuration.nix")
    libcalamares.utils.host_env_process_output(
        ["cp", "/dev/stdin", config_path], None, cfg
    )

    # Lay down the wrapper flake.nix.
    flake_path = os.path.join(root_mount_point, "etc/nixos/flake.nix")
    libcalamares.utils.host_env_process_output(
        ["cp", "/dev/stdin", flake_path], None, flake_nix
    )

    # Generate flake.lock by overriding every input spaces declares
    # with its pre-staged store path. Each `--override-input` tells nix
    # to lock that input against a `path:` ref, so the resulting lock
    # has zero github fetches and the install runs offline. The user's
    # post-install `nix flake update spaces` rewrites the lock back to
    # canonical github.
    flake_dir = os.path.join(root_mount_point, "etc/nixos")
    nixFlakeLockCmd = ["pkexec"]
    nixFlakeLockCmd.extend(generateProxyStrings())
    nixFlakeLockCmd.extend(
        [
            "nix",
            "--extra-experimental-features",
            "nix-command flakes",
            "flake",
            "lock",
            flake_dir,
            "--override-input",
            "spaces",
            "path:" + SPACES_FLAKE_PATH,
        ]
    )
    for name, path in INPUT_OVERRIDES.items():
        nixFlakeLockCmd.extend(["--override-input", "spaces/" + name, "path:" + path])
    try:
        subprocess.check_output(nixFlakeLockCmd, stderr=subprocess.STDOUT)
    except subprocess.CalledProcessError as e:
        libcalamares.utils.error("nix flake lock failed:\n" + e.output.decode("utf8"))
        return (
            _("Building the system configuration failed"),
            _(e.output.decode("utf8")),
        )

    status = _("Installing Spaces OS")
    libcalamares.job.setprogress(0.3)

    try:
        subprocess.check_output(
            ["pkexec", "chmod", "755", root_mount_point],
            stderr=subprocess.STDOUT,
        )
    except subprocess.CalledProcessError as e:
        libcalamares.utils.warning(
            "Failed to set permissions on {}: {}".format(root_mount_point, e.output)
        )

    # Build the system toplevel out-of-band, then hand it to
    # nixos-install via `--system`. We avoid `nixos-install --flake`
    # because nix#9339 (lock-rewrite cycle on path-flakes) is unfixed
    # as of 2026-04. `--no-write-lock-file` keeps our pre-written
    # lock untouched, so the wrapper's narHash is stable mid-install.
    hostname = gs.value("hostname") or "nixos"
    flake_ref = "path:{}#nixosConfigurations.{}.config.system.build.toplevel".format(
        os.path.join(root_mount_point, "etc/nixos"), hostname
    )
    nixBuildCmd = ["pkexec"]
    nixBuildCmd.extend(generateProxyStrings())
    nixBuildCmd.extend(
        [
            "nix",
            "--extra-experimental-features",
            "nix-command flakes",
            "build",
            flake_ref,
            "--no-link",
            "--print-out-paths",
            "--no-write-lock-file",
        ]
    )
    try:
        output_lines = []
        proc = subprocess.Popen(
            nixBuildCmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT
        )
        while True:
            line = proc.stdout.readline().decode("utf-8", errors="replace")
            if not line and proc.poll() is not None:
                break
            if line:
                output_lines.append(line)
                libcalamares.utils.debug("nix build: {}".format(line.rstrip()))
        rc = proc.wait()
        out = "".join(output_lines)
        if rc != 0:
            libcalamares.utils.error("nix build failed:\n" + out)
            return (_("Building the system configuration failed"), _(out))
        # Last non-empty line is the toplevel store path.
        toplevel = next(line.strip() for line in reversed(output_lines) if line.strip())
    except OSError as e:
        libcalamares.utils.error("nix build invocation failed: " + str(e))
        return (_("Building the system configuration failed"), str(e))

    nixosInstallCmd = ["pkexec"]
    nixosInstallCmd.extend(generateProxyStrings())
    nixosInstallCmd.extend(
        [
            "nixos-install",
            "--no-root-passwd",
            "--root",
            root_mount_point,
            "--system",
            toplevel,
            # See upstream comment: realign nix's build-dir so chroot
            # under /tmp doesn't trip the no-world-writable-parent rule.
            "--option",
            "build-dir",
            "/nix/var/nix/builds",
        ]
    )

    try:
        output = ""
        proc = subprocess.Popen(
            nixosInstallCmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT
        )
        while True:
            line = proc.stdout.readline().decode("utf-8")
            output += line
            libcalamares.utils.debug("nixos-install: {}".format(line.strip()))
            if not line:
                break
        if proc.wait() != 0:
            return (_("nixos-install failed"), _(output))
    except Exception:
        return (_("nixos-install failed"), _("Installation failed to complete"))

    return None
