package main

// Wire protocol for app-coordinator.
//
// One JSON object per request, one JSON object per reply. Connections
// are short-lived: a caller writes its Request, reads back the Reply,
// and closes. Subscribing to a long-lived event stream is not part of
// v1 — callers poll `running` if they need to.

// Request is sent by the caller. Fields are op-specific; unused
// fields are omitted in JSON.
type Request struct {
	Op   string   `json:"op"`             // "list" | "spawn" | "running" | "kill"
	App  string   `json:"app,omitempty"`  // spawn
	Args []string `json:"args,omitempty"` // spawn — appended to the launcher argv
	Unit string   `json:"unit,omitempty"` // kill
}

// Reply is what the coordinator writes back. Op is "ok" on success
// and "error" otherwise; the result fields are populated per request.
type Reply struct {
	Op      string       `json:"op"`
	Apps    []string     `json:"apps,omitempty"`    // list
	Running []RunningApp `json:"running,omitempty"` // running
	Unit    string       `json:"unit,omitempty"`    // spawn (informational; the actual unit name is assigned by the launcher)
	Info    *ManifestApp `json:"info,omitempty"`    // info — the requested app's manifest entry
	Error   string       `json:"error,omitempty"`
}

// RunningApp is one entry returned by the `running` op. The unit name
// follows the launcher's `app-<name>-<pid>.service` pattern.
type RunningApp struct {
	App  string `json:"app"`
	Unit string `json:"unit"`
}

// Manifest is the at-rest config the Nix module renders to disk. The
// coordinator reads it once at startup; restart the unit to pick up
// changes (the module's restartTriggers wire it to the manifest path).
type Manifest struct {
	Apps map[string]ManifestApp `json:"apps"`
}

// ManifestApp records everything the coordinator needs to launch an
// app, plus enough metadata for operators (and a future grant UI)
// to see what each app declared. LauncherPath is the absolute
// /nix/store path of the `app-run-<name>` script generated by the
// apps module. AllowedArgs is a list of Go RE2 regex patterns;
// runtime args supplied by coordinator callers must each match at
// least one pattern, otherwise the spawn is rejected. SpawnableBy
// lists caller app-ids permitted to launch this app via the
// coordinator; `"*"` allows any caller (including the operator
// from the host shell), `"host"` matches any caller that isn't
// itself inside a managed app sandbox.
//
// Granted / Requested / Denied mirror the manifest's permission
// triple — pure introspection data; the launcher script already
// has them baked in, the coordinator only republishes them so
// operators don't need to read /nix/store launcher scripts.
type ManifestApp struct {
	LauncherPath string   `json:"launcherPath"`
	AllowedArgs  []string `json:"allowedArgs"`
	SpawnableBy  []string `json:"spawnableBy"`
	AppId        string   `json:"appId,omitempty"`
	Granted      []string `json:"granted,omitempty"`
	Requested    []string `json:"requested,omitempty"`
	Denied       []string `json:"denied,omitempty"`
}
